namespace Te.Input;

/// <summary>
/// Portable key encoding adapted from the ConsoleEx slice that was itself based
/// on Terminal.Gui. The enum combines a base key with modifier masks so higher
/// layers can store shortcuts and compare key gestures without depending on
/// platform-specific console APIs.
/// </summary>
[Flags]
public enum KeyCode : uint
{
    CharMask = 0x_f_ffff,
    SpecialMask = 0x_fff0_0000,
    ShiftMask = 0x_1000_0000,
    CtrlMask = 0x_4000_0000,
    AltMask = 0x_8000_0000,

    Null = 0,
    Backspace = 8,
    Tab = 9,
    Enter = ConsoleKey.Enter,
    Clear = 12,
    Esc = 27,
    Space = 32,

    D0 = 48,
    D1,
    D2,
    D3,
    D4,
    D5,
    D6,
    D7,
    D8,
    D9,

    A = 65,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    MaxCodePoint = 0x10FFFF,
    CursorUp = MaxCodePoint + ConsoleKey.UpArrow,
    CursorDown = MaxCodePoint + ConsoleKey.DownArrow,
    CursorLeft = MaxCodePoint + ConsoleKey.LeftArrow,
    CursorRight = MaxCodePoint + ConsoleKey.RightArrow,
    PageUp = MaxCodePoint + ConsoleKey.PageUp,
    PageDown = MaxCodePoint + ConsoleKey.PageDown,
    Home = MaxCodePoint + ConsoleKey.Home,
    End = MaxCodePoint + ConsoleKey.End,
    Insert = MaxCodePoint + ConsoleKey.Insert,
    Delete = MaxCodePoint + ConsoleKey.Delete,
    PrintScreen = MaxCodePoint + ConsoleKey.PrintScreen,
    F1 = MaxCodePoint + ConsoleKey.F1,
    F2 = MaxCodePoint + ConsoleKey.F2,
    F3 = MaxCodePoint + ConsoleKey.F3,
    F4 = MaxCodePoint + ConsoleKey.F4,
    F5 = MaxCodePoint + ConsoleKey.F5,
    F6 = MaxCodePoint + ConsoleKey.F6,
    F7 = MaxCodePoint + ConsoleKey.F7,
    F8 = MaxCodePoint + ConsoleKey.F8,
    F9 = MaxCodePoint + ConsoleKey.F9,
    F10 = MaxCodePoint + ConsoleKey.F10,
    F11 = MaxCodePoint + ConsoleKey.F11,
    F12 = MaxCodePoint + ConsoleKey.F12,
    F13 = MaxCodePoint + ConsoleKey.F13,
    F14 = MaxCodePoint + ConsoleKey.F14,
    F15 = MaxCodePoint + ConsoleKey.F15,
    F16 = MaxCodePoint + ConsoleKey.F16,
    F17 = MaxCodePoint + ConsoleKey.F17,
    F18 = MaxCodePoint + ConsoleKey.F18,
    F19 = MaxCodePoint + ConsoleKey.F19,
    F20 = MaxCodePoint + ConsoleKey.F20,
    F21 = MaxCodePoint + ConsoleKey.F21,
    F22 = MaxCodePoint + ConsoleKey.F22,
    F23 = MaxCodePoint + ConsoleKey.F23,
    F24 = MaxCodePoint + ConsoleKey.F24,
}
